project_name: FGVC-HERBS_no_amp
notes: 'no inverse'
exp_name: basline
use_wandb: True
wandb_entity: poyung
train_root: ./bird_data/train/
val_root: ./bird_data/test/
data_size: 384
num_workers: 2
batch_size: 4
model_name: swin-t
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0003
max_epochs: 30
warmup_batchs: 1500
use_amp: False
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 200
num_selects: 
  layer1: 128
  layer2: 128
  layer3: 64
  layer4: 32
use_combiner: True
lambda_b0: 1.375
lambda_b: 0.3
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 4
log_freq: 100
eval_freq: 5
temperature: 75
